# Generated by Django 4.2.30 on 2026-09-01 21:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Customer Code')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(db_index=True, max_length=50, verbose_name='Voucher / Document Number')),
                ('date', models.DateField(db_index=True, verbose_name='Transaction Date')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Debit Amount (بدهکار)')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Credit Amount (بستانکار)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / Note')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference Document / Invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='accounting.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['customer', 'date'], name='idx_voucher_cust_date'), models.Index(fields=['date'], name='idx_voucher_date')],
            },
        ),
    ]
