# Generated by Django 6.0.7 on 2026-09-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['date', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='idx_voucher_date',
        ),
    ]
