# Generated by Django 4.2.30 on 2026-09-02 09:33

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_redundant_voucher_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voucher',
            name='idx_voucher_cust_date',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='idx_cust_code_lower'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['customer', 'date', 'id'], name='idx_voucher_cust_date_id'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['date', 'id'], name='idx_voucher_date_id'),
        ),
    ]
